export const ROUTES = {
  SPLASH: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  CONTACTS: "/contacts",
  INCOMING_CALL: "/call/incoming",
  OUTGOING_CALL: "/call/outgoing",
  ACTIVE_CALL: "/call/active/:callId",
  GROUP_CALL: "/call/group/:callId",
  DETECTION_REPORTS: "/detection-reports",
  CALL_HISTORY: "/call-history",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  NOT_FOUND: "*",
} as const;